### ISSUE TITLE
Need a ListAtists Command

### ISSUE THREAD

**Issue by timgray** [RafaelEstevamReis/SimpleMPD#1]
There is no way to list the artists in the database so you can present the user with a list of artist to choose from

**Comment by RafaelEstevamReis** [comment]
I peeked at the MPD protocol documentation
https://mpd.readthedocs.io/en/latest/protocol.html

And did not find any command for list artists
I found only `stats` -> `artists`
Which command you refer to?

**Comment by RafaelEstevamReis** [comment]
Maybe  `The music database` -> `count group artist`?
Or  `The music database` -> `list {TYPE} {FILTER} [group {GROUPTYPE}]`, like `list album group albumartist`?

**Comment by timgray** [comment]
list command does it

send list[space]artist[carriage return] delivers a list of the artists.
or just expose the list command without any forced searches in it.

![SNAG-0000- 2023 08 07 13 44](https://github.com/RafaelEstevamReis/SimpleMPD/assets/8658785/52e18e99-81b6-4747-959d-5b3ede58b58a)

**Comment by RafaelEstevamReis** [comment]
I'll try some tests when I got home

> or just expose the list command
Is better to expose the "list" (or GroupCount)

But I'll try booth then we test it

**Comment by RafaelEstevamReis** [comment]
I cannot test (yet - still at work) but can you take a look at these (4ad15f2) changes?

**Comment by RafaelEstevamReis** [comment]
I managed to implement:
`List(expression)`
and
`List(Tags.Artist)`

But any of the filters worked (like I did for search and Find)
Check it out d4ef23c

**Comment by timgray** [comment]
This is awesome thank you.    I have been traveling so I will start using this as soon as possible!  Thank you very much!

**Comment by RafaelEstevamReis** [comment]
You're welcome,
Test when you can, and in case of any problems, open a new issue and I'll
take a look at it
